language: python
install:
  - pip install mkdocs mkdocs_bootswatch mkdocs_bootstrap
script:
  - mkdocs build
after_success:
  - >-
    git remote add gh_deploy
    "https://${GH_TOKEN}@github.com/SAINTConHHV/HHVLabs"
  - git remote update
  - ./mkdocs_deploy.sh
env:
  global:
    - secure: >-
        MElTbVQeiMw7vycyVNmPsOyV9kI1WMeQF8DuZ9vNL5Dd5ggC6ggP1ZmIINO0HCRB970T3XVFVQqazdcqp4EmaViEcmEAeZLaRNJ98VCIoJrPcbSkm9GxMjzDwB51IIAsIELq2JCPCdVrdRcVGaLrFArFECUzEm+pNz9U1LwTmXx8qVZvDi9AZmgZe9OPGh9i9HoF6t19TVvRVjwFPtcZMXZ618bz4HVpHtfXJFFiP/hJw9npU5lgkM9D4BdwuEYK4J5gnIEnUZDloEWVHtc3lsbmd5Rh41zD+YrVunQ7Gs2LLu2tURIE9Tp5ZQlhh1ezZ3W0l9SVAOleW81SO5YTxtx/euFSVkn0+6iMUf/FQC+61ZuZqD+wKQ9teMkqL2fLLd/vPvAgwrpPJEJzjOXlaR2icjV/Z+XXY57UKNUj1c18XLrfIhr8la6MYP5pZhzJ51Ea4C21IdR/Ei9QqqhJIeWFUhlj7AGGBmoHvX4MN0Rc9uvqytdGi6TsVzwq54ZSXLKODPmFtDJ7MZHzxH9mCm/Cf5QDnnCmoEQI80FTL5rk5CyB4zz6/MQbMkmxEi8HwEJRe9ch49XZ/BuxqTYpDG0K9+dGYEH4539/nYgiK7+dISNizrfkKwNe7NtUN9NWn7dDjaBXqvP+24oYjFdylRJucW5GZNRjONQlLicImOA=
