language: python
install:
  - pip install mkdocs mkdocs_bootswatch mkdocs_bootstrap
script:
  - mkdocs build
after_success:
  - >-
    git remote add gh_deploy
    "https://${GH_TOKEN}@github.com/SAINTConHHV/HHVLabs"
  - ./mkdocs_deploy.sh
  - git status
  - git log gh_deploy/gh-pages -2
  - git log gh-pages -2
env:
  global:
    - secure: >-
        eac+TcNNlZrynj1Fg0W2d0KvlZoNda07/l3XLGLUlqaWUyn/oy7K+eb9PgfsN2b+GXEL+f7IGT3110+GVX8e+9NO2rCILU+We/LwoFBP5RlTIJkE4qJn93ibrEm2qG3lHAxvdj0UsmF/FCvMUD8Jdaeaq4edM23Pvv1Tb2mKJj3B0BRCSIFhaXJMhtrWf9HQwoo7Wh3xIDOmSw98bhIVu5domlDy1Maz+QyfRvhurRa5vc2/ItV/bvqmGy1f3cZ57c5+0jhw0zau5t9tgFZ51mg3lxr9+8MazxqUR1etNU49gEDMcsP0S8pPsbuHrK7iOLaZGo4DSm74XT53AUB1dE0HFX8FDR0yoEyfu76LN71t+ekQfcP1VD6ZKPmIDQdjQD5suIJ6zSGJi+ueS8NaCOV3SleXC0BPESVkMG2umMak1BEKFzM9X+M6HjhBfwP1RQVHRhMJ1I/oh6ebLlQF+GuN54SOJ0FXM9KrTy54ft+hYpBx12J9JTTyRYs7cIKlabFmj4AfRH/2rSeRuUCzTkwnBebhld5R4xHF3YRXzHkhtu3HAytuemRTWfEY7m+8dvnNqVA5S2PFsFYdpBQrW4gKZhawn4FHSXV00u2yTDm2jEYLnjE1zpjb8YJUx8ln0dlwIpBHdHD9entKtvYdWpzm7ta3x9RBzuVHFrUNVgk=
