FROM resin/%%RESIN_MACHINE_NAME%%-python

# Install wget and curl
RUN apt-get update && apt-get install -y \
  wget \
  curl && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
  python-pyudev \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade termcolor esptool pyudev

WORKDIR /usr/src/app

COPY autoflash_badge.py ./

ENV INITSYSTEM on

CMD ["python", "autoflash_badge.py"]
