site_name: HHVLabs
repo_url: 'https://github.com/SAINTConHHV/HHVLabs/'
site_url: 'https://saintconhhv.github.io/HHVLabs/'
#edit_uri: 'edit/master/docs/'
markdown_extensions:
    - attr_list
pages:
- Home: 'index.md'
- Labs:
        - '2016':
                - 'rtl-sdr: ADS-B with adstoolbox': 'walkthroughs/ads-b.md'
                - 'rubber ducky: Empire with a ducky': 'walkthroughs/empire-ducky.md'
                - 'HackRF: RC Car': 'walkthroughs/hackrf-rc-car.md'
                - 'Proxmark: Introduction': 'walkthroughs/proxmark.md'
                - 'WiFi Pineapple: Rogue Captive Portal': 'walkthroughs/pineapple-captive-portal.md'
                - 'Software': 'software-2016.md'
- deleteme: 'walkthroughs/template.md'
#theme: readthedocs
theme: slate
