site_name: HHVLabs
pages:
- Home: 'index.md'
- Labs:
        - '2016':
                - 'HackRF RC Car': 'walkthroughs/hackrf-rc-car.md'
                - 'Software': 'software-2016.md'
theme: slate
